# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.14.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: trunk-fmt
        name: universal code formatter
        entry: ./trunk fmt --force
        language: system
