services:
  mkdocs:
    container_name: mkdocs
    image: ckwing/duospaced-mkdocs-material:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        DEBUG: ''
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    volumes:
      - .:/docs
