name: Deploy Docs
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with MkDocs Material Docker image
        run: |
          docker run --rm -v ${PWD}:/docs -v ~/.ssh:/root/.ssh ckwing/duospaced-mkdocs-material:latest gh-deploy --force
